source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors", "~> 2.0"
gem "bootsnap", "~> 1.18", require: false

group :development, :test do
  gem "rspec-rails", "~> 6.1"
end
